"""
Sends the generated HTML report via the corporate Outlook/Office 365 mailbox.

Setup required (see README.md for full steps):
1. A dedicated mailbox, e.g. research@bridgecapital.com.
2. An "app password" for that mailbox (requires SMTP AUTH enabled by IT and,
   if MFA is on, an app password generated in the Microsoft account portal).
3. Environment variables / GitHub secrets: EMAIL_ADDRESS, EMAIL_PASSWORD,
   EMAIL_RECIPIENTS.

If your organization disables basic SMTP AUTH entirely (common in stricter
Microsoft 365 tenants), you'll need to switch this function to use the
Microsoft Graph API with OAuth2 client-credentials instead — flag this to
your IT team early, as it changes the auth flow (see README "Alternative:
Microsoft Graph API").
"""

import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASSWORD, FROM_NAME, RECIPIENTS

EMAIL_TEMPLATE = """
<div style="font-family:Georgia,serif; max-width:700px; margin:0 auto; padding:24px; color:#1a1a1a;">
  <div style="border-bottom:3px solid #0a3d62; padding-bottom:12px; margin-bottom:20px;">
    <h1 style="font-size:20px; color:#0a3d62; margin:0;">Bridge Capital Partners</h1>
    <p style="font-size:13px; color:#666; margin:4px 0 0 0;">{subtitle} &middot; {date_str}</p>
  </div>
  {body}
  <div style="border-top:1px solid #ddd; margin-top:32px; padding-top:12px; font-size:11px; color:#999;">
    Generated by the Bridge Capital Partners Research Agent. For internal use only —
    not investment advice. Please verify figures against primary sources before external use.
  </div>
</div>
"""


def send_report(subject: str, subtitle: str, date_str: str, html_body: str,
                 recipients: list[str] | None = None) -> None:
    to_list = recipients or RECIPIENTS
    if not to_list:
        raise ValueError("No recipients configured (EMAIL_RECIPIENTS is empty).")

    full_html = EMAIL_TEMPLATE.format(subtitle=subtitle, date_str=date_str, body=html_body)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"{FROM_NAME} <{SMTP_USER}>"
    msg["To"] = ", ".join(to_list)
    msg.attach(MIMEText(full_html, "html"))

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
        server.starttls()
        server.login(SMTP_USER, SMTP_PASSWORD)
        server.sendmail(SMTP_USER, to_list, msg.as_string())

    print(f"Sent '{subject}' to {len(to_list)} recipient(s).")
