"""
Sends the generated HTML report via the Gmail API using OAuth2, instead of
SMTP + username/password. This is required because Google Workspace admins
can (and often do) disable "App Passwords" org-wide, which breaks the
simpler SMTP approach.

Setup required (see README.md section "Gmail API setup" for full steps):
1. A Google Cloud project with the Gmail API enabled.
2. An OAuth2 "Desktop app" client (client_id + client_secret).
3. A one-time authorization run (generate_token.py) to obtain a refresh_token
   for alexandre.leao@bdcp.com.br.
4. Environment variables / GitHub secrets: GMAIL_CLIENT_ID, GMAIL_CLIENT_SECRET,
   GMAIL_REFRESH_TOKEN, EMAIL_ADDRESS, EMAIL_RECIPIENTS.
"""

import base64
import requests
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from config import (
    GMAIL_SENDER,
    GMAIL_CLIENT_ID,
    GMAIL_CLIENT_SECRET,
    GMAIL_REFRESH_TOKEN,
    FROM_NAME,
    RECIPIENTS,
)

TOKEN_URL = "https://oauth2.googleapis.com/token"
SEND_URL = "https://gmail.googleapis.com/gmail/v1/users/me/messages/send"

EMAIL_TEMPLATE = """
<div style="font-family:Georgia,serif; max-width:700px; margin:0 auto; padding:24px; color:#1a1a1a;">
  <div style="border-bottom:3px solid #0a3d62; padding-bottom:12px; margin-bottom:20px;">
    <h1 style="font-size:20px; color:#0a3d62; margin:0;">Bridge Capital Partners</h1>
    <p style="font-size:13px; color:#666; margin:4px 0 0 0;">{subtitle} &middot; {date_str}</p>
  </div>
  {body}
  <div style="border-top:1px solid #ddd; margin-top:32px; padding-top:12px; font-size:11px; color:#999;">
    Generated by the Bridge Capital Partners Research Agent. For internal use only —
    not investment advice. Please verify figures against primary sources before external use.
  </div>
</div>
"""


def _get_access_token() -> str:
    """Exchange the long-lived refresh_token for a short-lived access_token."""
    resp = requests.post(
        TOKEN_URL,
        data={
            "client_id": GMAIL_CLIENT_ID,
            "client_secret": GMAIL_CLIENT_SECRET,
            "refresh_token": GMAIL_REFRESH_TOKEN,
            "grant_type": "refresh_token",
        },
        timeout=30,
    )
    resp.raise_for_status()
    return resp.json()["access_token"]


def send_report(subject: str, subtitle: str, date_str: str, html_body: str,
                 recipients: list[str] | None = None) -> None:
    to_list = recipients or RECIPIENTS
    if not to_list:
        raise ValueError("No recipients configured (EMAIL_RECIPIENTS is empty).")

    full_html = EMAIL_TEMPLATE.format(subtitle=subtitle, date_str=date_str, body=html_body)

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"] = f"{FROM_NAME} <{GMAIL_SENDER}>"
    msg["To"] = ", ".join(to_list)
    msg.attach(MIMEText(full_html, "html"))

    raw = base64.urlsafe_b64encode(msg.as_bytes()).decode("utf-8")

    access_token = _get_access_token()
    resp = requests.post(
        SEND_URL,
        headers={
            "Authorization": f"Bearer {access_token}",
            "Content-Type": "application/json",
        },
        json={"raw": raw},
        timeout=60,
    )
    if not resp.ok:
        # Print Google's detailed error body before raising, so the real
        # cause (bad scope, API not enabled, org policy block, etc.) shows
        # up in the GitHub Actions log instead of just "403 Forbidden".
        print("Gmail API error response body:", resp.text)
    resp.raise_for_status()

    print(f"Sent '{subject}' to {len(to_list)} recipient(s).")
